export type Lang = "hi" | "en";

const content = {
  hi: {
    brandEn: "ExamsExpress",
    brandHi: "MP राज्य स्तरीय परीक्षाएँ",
    navCta: "लॉगिन / रजिस्टर",
    eyebrow: "MP पुलिस SI / सूबेदार · प्रीलिम्स · 2026",
    heroTitlePre: "परीक्षा हॉल में ",
    heroTitleAccent: "पहली बार",
    heroTitlePost: " कंप्यूटर पर टेस्ट मत दीजिए",
    heroLede:
      "MP SI / सूबेदार की असली ऑनलाइन परीक्षा जैसा मॉक टेस्ट — वही 100 प्रश्न, वही 2 घंटे, कोई नेगेटिव मार्किंग नहीं। MPESB भर्ती 2026 की अधिसूचना जारी, 9 सितंबर से आवेदन। पहला फुल टेस्ट बिल्कुल मुफ़्त, बिना कार्ड डिटेल के।",
    ctaPrimary: "फ्री टेस्ट शुरू करें →",
    ctaGhost: "एग्ज़ाम पैटर्न देखें",
    stats: [
      { value: "100", label: "कुल प्रश्न" },
      { value: "100", label: "कुल अंक" },
      { value: "2 घं.", label: "अवधि" },
      { value: "₹0", label: "पहला टेस्ट" },
    ],
    admitCard: {
      t1: "PRACTICE HALL TICKET",
      t2: "अभ्यास प्रवेश पत्र",
      name: "उम्मीदवार का नाम",
      role: "MP SI / सूबेदार · प्रीलिम्स",
      rows: [
        { label: "परीक्षा", value: "PRELIMS MOCK 01" },
        { label: "कुल प्रश्न", value: "100" },
        { label: "कुल अंक", value: "100" },
        { label: "अवधि", value: "120 MIN" },
        { label: "नेगेटिव मार्किंग", value: "नहीं" },
      ],
      stamp: "फ्री टेस्ट",
    },
    stepsKicker: "प्रोसेस",
    stepsTitle: "तीन स्टेप में शुरुआत",
    steps: [
      { num: "01 / लॉगिन", title: "अकाउंट बनाएं", desc: "मोबाइल नंबर या Google से 30 सेकंड में रजिस्टर करें, कोई फॉर्म नहीं भरना।" },
      { num: "02 / फ्री टेस्ट", title: "1 फुल टेस्ट मुफ़्त दें", desc: "असली परीक्षा जैसा इंटरफ़ेस — टाइमर, सेक्शन नेविगेशन, इंस्टेंट स्कोरकार्ड।" },
      { num: "03 / पैकेज", title: "5, 10 या 20 टेस्ट लें", desc: "अपनी तैयारी के हिसाब से पैकेज चुनें और लगातार प्रैक्टिस करें।" },
    ],
    patternKicker: "एग्ज़ाम पैटर्न",
    patternTitle: "हर मॉक प्रीलिम्स पैटर्न पर बना है",
    patternSubjectHeader: "विवरण",
    patternWeightHeader: "जानकारी",
    patternRows: [
      { subject: "परीक्षा मोड", weight: "ऑनलाइन (CBT)" },
      { subject: "कुल प्रश्न", weight: "100" },
      { subject: "कुल अंक", weight: "100" },
      { subject: "अवधि", weight: "2 घंटे" },
      { subject: "नेगेटिव मार्किंग", weight: "नहीं" },
    ],
    patternBig: "100",
    patternNote:
      "प्रीलिम्स क्वालिफाइंग है (अंक अंतिम चयन में नहीं जुड़ते)। विषय: सामान्य ज्ञान, सामान्य विज्ञान, गणित एवं तर्कशक्ति, सामान्य हिंदी, समसामयिकी, कंप्यूटर, म.प्र. सामान्य ज्ञान। विषयवार अंक-वितरण व मेन्स पैटर्न (नेगेटिव मार्किंग सहित) की पुष्टि के लिए आधिकारिक अधिसूचना esb.mp.gov.in देखें।",
    whyKicker: "क्यों ज़रूरी है",
    whyTitle: "ऑनलाइन प्रैक्टिस के बिना असली परीक्षा में झटका लगता है",
    whyCards: [
      { icon: "क", title: "कंप्यूटर स्क्रीन की आदत", desc: "बहुत से उम्मीदवार पहली बार माउस से आंसर सेलेक्ट करना परीक्षा हॉल में सीखते हैं। यहाँ पहले से अभ्यास हो जाता है।" },
      { icon: "स", title: "समय का दबाव", desc: "असली टाइमर के साथ अभ्यास करने से पता चलता है कि कौन सा सेक्शन ज़्यादा समय ले रहा है, एग्ज़ाम में सरप्राइज़ नहीं मिलता।" },
      { icon: "रि", title: "इंस्टेंट रिज़ल्ट", desc: "हर टेस्ट के बाद तुरंत सेक्शन-वाइज़ स्कोर और कमज़ोर विषय पता चलते हैं, अगली तैयारी उसी हिसाब से करें।" },
    ],
    pricingKicker: "पैकेज",
    pricingTitle: "पहला टेस्ट मुफ़्त, फिर अपनी ज़रूरत के हिसाब से पैकेज चुनें",
    plans: [
      { name: "फ्री ट्रायल", amount: "₹0", per: "1 फुल टेस्ट", features: ["असली परीक्षा इंटरफ़ेस", "इंस्टेंट स्कोरकार्ड", "कोई कार्ड डिटेल नहीं"], cta: "अभी शुरू करें" },
      { name: "स्टार्टर", amount: "₹399", per: "5 टेस्ट", features: ["5 फुल-लेंथ मॉक टेस्ट", "सेक्शन-वाइज़ एनालिसिस", "60 दिन वैलिडिटी"], cta: "पैकेज लें" },
      { name: "पॉपुलर", amount: "₹799", per: "10 टेस्ट", features: ["10 फुल-लेंथ मॉक टेस्ट", "डिटेल्ड परफॉर्मेंस रिपोर्ट", "90 दिन वैलिडिटी"], cta: "पैकेज लें", tag: "सबसे लोकप्रिय" },
      { name: "प्रो", amount: "₹1499", per: "20 टेस्ट", features: ["20 फुल-लेंथ मॉक टेस्ट", "प्रोग्रेस ट्रैकिंग", "120 दिन वैलिडिटी"], cta: "पैकेज लें" },
    ],
    faqKicker: "सवाल-जवाब",
    faqTitle: "अक्सर पूछे जाने वाले सवाल",
    faqs: [
      { q: "MP SI / सूबेदार प्रीलिम्स में कितने प्रश्न और कितने अंक होते हैं?", a: "उपलब्ध जानकारी के अनुसार प्रीलिम्स में 100 प्रश्न, 100 अंक और 2 घंटे की अवधि होती है, और इसमें कोई नेगेटिव मार्किंग नहीं होती। परीक्षा कंप्यूटर आधारित (CBT) होती है।" },
      { q: "क्या प्रीलिम्स में नेगेटिव मार्किंग है?", a: "उपलब्ध जानकारी के अनुसार प्रीलिम्स में नेगेटिव मार्किंग नहीं है और यह क्वालिफाइंग होती है। मेन्स परीक्षा में नेगेटिव मार्किंग (1/3) लागू होती है — पुष्टि के लिए आधिकारिक अधिसूचना देखें।" },
      { q: "क्या मैं मोबाइल से टेस्ट दे सकता हूं?", a: "हां, टेस्ट मोबाइल और कंप्यूटर दोनों पर चलता है, लेकिन असली परीक्षा अनुभव के लिए कंप्यूटर या लैपटॉप पर प्रैक्टिस करने की सलाह दी जाती है।" },
      { q: "क्या यह MPESB की आधिकारिक परीक्षा या वेबसाइट है?", a: "नहीं, ये एक स्वतंत्र प्रैक्टिस प्लेटफ़ॉर्म है। हम MPESB से जुड़े नहीं हैं, हमारे टेस्ट सिर्फ़ आधिकारिक अधिसूचना में बताए गए पैटर्न और सिलेबस पर आधारित होते हैं। ताज़ा जानकारी के लिए esb.mp.gov.in देखें।" },
    ],
    finalTitle: "आज ही अपना पहला MP SI प्रीलिम्स मॉक टेस्ट दें",
    finalDesc: "बिल्कुल मुफ़्त, बिना कार्ड डिटेल के, सिर्फ़ 5 मिनट में शुरू करें।",
    finalCta: "फ्री टेस्ट शुरू करें →",
    footer: "ExamsExpress · MP SI / सूबेदार टेस्ट सीरीज़ — MPESB से असंबद्ध एक स्वतंत्र प्रैक्टिस प्लेटफ़ॉर्म",
    footerLinks: { about: "हमारे बारे में", howItWorks: "यह कैसे काम करता है", disclaimer: "डिस्क्लेमर व नीतियाँ" },
  },
  en: {
    brandEn: "ExamsExpress",
    brandHi: "MP State-Level Exams",
    navCta: "Login / Register",
    eyebrow: "MP Police SI / Subedar · Prelims · 2026",
    heroTitlePre: "Don't take a computer-based test for the ",
    heroTitleAccent: "first time",
    heroTitlePost: " in the exam hall",
    heroLede:
      "A mock test that replicates the real MP SI / Subedar online exam — the same 100 questions, the same 2 hours, no negative marking. The MPESB 2026 notification is out, applications from 9 September. Your first full test is completely free, no card required.",
    ctaPrimary: "Start Free Test →",
    ctaGhost: "View Exam Pattern",
    stats: [
      { value: "100", label: "Questions" },
      { value: "100", label: "Total Marks" },
      { value: "2 hr", label: "Duration" },
      { value: "₹0", label: "First Test" },
    ],
    admitCard: {
      t1: "PRACTICE HALL TICKET",
      t2: "Practice Admit Card",
      name: "Candidate Name",
      role: "MP SI / Subedar · Prelims",
      rows: [
        { label: "Exam", value: "PRELIMS MOCK 01" },
        { label: "Total Questions", value: "100" },
        { label: "Total Marks", value: "100" },
        { label: "Duration", value: "120 MIN" },
        { label: "Negative Marking", value: "None" },
      ],
      stamp: "FREE TEST",
    },
    stepsKicker: "PROCESS",
    stepsTitle: "Get started in three steps",
    steps: [
      { num: "01 / LOGIN", title: "Create an account", desc: "Register with your mobile number or Google in 30 seconds, no forms to fill." },
      { num: "02 / FREE TEST", title: "Take 1 full test free", desc: "A real exam-like interface — timer, section navigation, instant scorecard." },
      { num: "03 / PACKAGE", title: "Get 5, 10 or 20 tests", desc: "Choose a package based on your preparation and practice consistently." },
    ],
    patternKicker: "EXAM PATTERN",
    patternTitle: "Every mock follows the Prelims pattern",
    patternSubjectHeader: "Detail",
    patternWeightHeader: "Information",
    patternRows: [
      { subject: "Exam mode", weight: "Online (CBT)" },
      { subject: "Total questions", weight: "100" },
      { subject: "Total marks", weight: "100" },
      { subject: "Duration", weight: "2 hours" },
      { subject: "Negative marking", weight: "None" },
    ],
    patternBig: "100",
    patternNote:
      "Prelims is qualifying (marks don't count toward final selection). Subjects: General Knowledge, General Science, Maths & Reasoning, General Hindi, Current Affairs, Computer, MP GK. For the exact section-wise marks and the Mains pattern (which has negative marking), confirm on the official MPESB notification at esb.mp.gov.in.",
    whyKicker: "WHY IT MATTERS",
    whyTitle: "Without online practice, the real exam is a shock",
    whyCards: [
      { icon: "1", title: "Getting used to a screen", desc: "Many candidates select answers with a mouse for the first time in the exam hall. Here, you practice it beforehand." },
      { icon: "2", title: "Time pressure", desc: "Practicing with a real timer shows which section is taking longer, so there are no surprises on exam day." },
      { icon: "3", title: "Instant results", desc: "Get section-wise scores and weak areas right after every test, and plan your next round of preparation accordingly." },
    ],
    pricingKicker: "PACKAGES",
    pricingTitle: "First test free, then pick a package that fits your needs",
    plans: [
      { name: "Free Trial", amount: "₹0", per: "1 full test", features: ["Real exam interface", "Instant scorecard", "No card required"], cta: "Start Now" },
      { name: "Starter", amount: "₹399", per: "5 tests", features: ["5 full-length mock tests", "Section-wise analysis", "60-day validity"], cta: "Get Package" },
      { name: "Popular", amount: "₹799", per: "10 tests", features: ["10 full-length mock tests", "Detailed performance report", "90-day validity"], cta: "Get Package", tag: "MOST POPULAR" },
      { name: "Pro", amount: "₹1499", per: "20 tests", features: ["20 full-length mock tests", "Progress tracking", "120-day validity"], cta: "Get Package" },
    ],
    faqKicker: "FAQ",
    faqTitle: "Frequently Asked Questions",
    faqs: [
      { q: "How many questions and marks are there in MP SI / Subedar Prelims?", a: "Per available information, Prelims has 100 questions, 100 marks and a 2-hour duration, with no negative marking. It is a computer-based test (CBT)." },
      { q: "Is there negative marking in Prelims?", a: "Per available information, there is no negative marking in Prelims and it is qualifying. The Mains exam does have negative marking (1/3). Confirm on the official notification." },
      { q: "Can I take the test on mobile?", a: "Yes, the test works on both mobile and computer, but for the most realistic exam experience, we recommend practicing on a computer or laptop." },
      { q: "Is this the official MPESB exam or website?", a: "No, this is an independent practice platform. We are not affiliated with MPESB — our tests are based only on the pattern and syllabus described in the official notification. For the latest information, visit esb.mp.gov.in." },
    ],
    finalTitle: "Take your first MP SI Prelims mock test today",
    finalDesc: "Completely free, no card required, get started in just 5 minutes.",
    finalCta: "Start Free Test →",
    footer: "ExamsExpress · MP SI / Subedar Test Series — an independent practice platform, not affiliated with MPESB",
    footerLinks: { about: "About", howItWorks: "How It Works", disclaimer: "Disclaimer & Policies" },
  },
} satisfies Record<Lang, unknown>;

export default content;
