export type Lang = "hi" | "en";

const content = {
  hi: {
    brandEn: "ExamsExpress",
    brandHi: "MP राज्य स्तरीय परीक्षाएँ",
    navCta: "लॉगिन / रजिस्टर",
    eyebrow: "MPPEB पैटर्न पर आधारित · 2026",
    heroTitlePre: "परीक्षा हॉल में ",
    heroTitleAccent: "पहली बार",
    heroTitlePost: " कंप्यूटर पर टेस्ट मत दीजिए",
    heroLede:
      "MP पटवारी की असली ऑनलाइन परीक्षा जैसा मॉक टेस्ट — वही टाइमर, वही सेक्शन, वही स्क्रीन। पहला फुल टेस्ट बिल्कुल मुफ़्त, बिना कार्ड डिटेल के।",
    ctaPrimary: "फ्री टेस्ट शुरू करें →",
    ctaGhost: "एग्ज़ाम पैटर्न देखें",
    stats: [
      { value: "200", label: "कुल अंक" },
      { value: "3", label: "घंटे की परीक्षा" },
      { value: "6", label: "विषय कवर" },
      { value: "₹0", label: "पहला टेस्ट" },
    ],
    admitCard: {
      t1: "PRACTICE HALL TICKET",
      t2: "अभ्यास प्रवेश पत्र",
      name: "उम्मीदवार का नाम",
      role: "MP पटवारी भर्ती परीक्षा",
      rows: [
        { label: "परीक्षा", value: "MOCK TEST 01" },
        { label: "कुल प्रश्न", value: "100" },
        { label: "कुल अंक", value: "200" },
        { label: "अवधि", value: "180 MIN" },
        { label: "मोड", value: "ऑनलाइन" },
      ],
      stamp: "फ्री टेस्ट",
    },
    stepsKicker: "प्रोसेस",
    stepsTitle: "तीन स्टेप में शुरुआत",
    steps: [
      { num: "01 / लॉगिन", title: "अकाउंट बनाएं", desc: "मोबाइल नंबर से 30 सेकंड में रजिस्टर करें, कोई फॉर्म नहीं भरना।" },
      { num: "02 / फ्री टेस्ट", title: "1 फुल टेस्ट मुफ़्त दें", desc: "असली परीक्षा जैसा इंटरफ़ेस — टाइमर, सेक्शन नेविगेशन, इंस्टेंट स्कोरकार्ड।" },
      { num: "03 / पैकेज", title: "5, 10 या 20 टेस्ट लें", desc: "अपनी तैयारी के हिसाब से पैकेज चुनें और लगातार प्रैक्टिस करें।" },
    ],
    patternKicker: "एग्ज़ाम पैटर्न",
    patternTitle: "हर मॉक टेस्ट इसी पैटर्न पर बना है",
    patternSubjectHeader: "विषय",
    patternWeightHeader: "वेटेज",
    patternRows: [
      { subject: "सामान्य ज्ञान", weight: "उच्च" },
      { subject: "सामान्य गणित एवं रीज़निंग", weight: "उच्च" },
      { subject: "सामान्य हिंदी", weight: "मध्यम" },
      { subject: "सामान्य अंग्रेज़ी", weight: "मध्यम" },
      { subject: "कंप्यूटर ज्ञान", weight: "मध्यम" },
      { subject: "ग्रामीण अर्थव्यवस्था एवं पंचायती राज", weight: "मध्यम" },
    ],
    patternBig: "200",
    patternNote:
      "कुल अंकों की ऑनलाइन परीक्षा, 3 घंटे की अवधि। MPPEB की आधिकारिक अधिसूचना के अनुसार पैटर्न अपडेट किया जाता है, ताकि आपकी तैयारी हमेशा नए फॉर्मैट से मेल खाए।",
    whyKicker: "क्यों ज़रूरी है",
    whyTitle: "ऑनलाइन प्रैक्टिस के बिना असली परीक्षा में झटका लगता है",
    whyCards: [
      { icon: "क", title: "कंप्यूटर स्क्रीन की आदत", desc: "बहुत से उम्मीदवार पहली बार माउस से आंसर सेलेक्ट करना परीक्षा हॉल में सीखते हैं। यहाँ पहले से अभ्यास हो जाता है।" },
      { icon: "स", title: "समय का दबाव", desc: "असली टाइमर के साथ अभ्यास करने से पता चलता है कि कौन सा सेक्शन ज़्यादा समय ले रहा है, एग्ज़ाम में सरप्राइज़ नहीं मिलता।" },
      { icon: "रि", title: "इंस्टेंट रिज़ल्ट", desc: "हर टेस्ट के बाद तुरंत सेक्शन-वाइज़ स्कोर और कमज़ोर विषय पता चलते हैं, अगली तैयारी उसी हिसाब से करें।" },
    ],
    pricingKicker: "पैकेज",
    pricingTitle: "पहला टेस्ट मुफ़्त, फिर अपनी ज़रूरत के हिसाब से पैकेज चुनें",
    plans: [
      { name: "फ्री ट्रायल", amount: "₹0", per: "1 फुल टेस्ट", features: ["असली परीक्षा इंटरफ़ेस", "इंस्टेंट स्कोरकार्ड", "कोई कार्ड डिटेल नहीं"], cta: "अभी शुरू करें" },
      { name: "स्टार्टर", amount: "₹399", per: "5 टेस्ट", features: ["5 फुल-लेंथ मॉक टेस्ट", "सेक्शन-वाइज़ एनालिसिस", "60 दिन वैलिडिटी"], cta: "पैकेज लें" },
      { name: "पॉपुलर", amount: "₹799", per: "10 टेस्ट", features: ["10 फुल-लेंथ मॉक टेस्ट", "डिटेल्ड परफॉर्मेंस रिपोर्ट", "90 दिन वैलिडिटी"], cta: "पैकेज लें", tag: "सबसे लोकप्रिय" },
      { name: "प्रो", amount: "₹1499", per: "20 टेस्ट", features: ["20 फुल-लेंथ मॉक टेस्ट", "प्रोग्रेस ट्रैकिंग", "120 दिन वैलिडिटी"], cta: "पैकेज लें" },
    ],
    faqKicker: "सवाल-जवाब",
    faqTitle: "अक्सर पूछे जाने वाले सवाल",
    faqs: [
      { q: "क्या ये MPPEB की आधिकारिक परीक्षा है?", a: "नहीं, ये एक स्वतंत्र प्रैक्टिस प्लेटफ़ॉर्म है। हम MPPEB से जुड़े नहीं हैं, हमारे टेस्ट सिर्फ़ आधिकारिक अधिसूचना में बताए गए पैटर्न और सिलेबस पर आधारित होते हैं।" },
      { q: "क्या नेगेटिव मार्किंग शामिल है?", a: "हां, अगर आधिकारिक परीक्षा में नेगेटिव मार्किंग लागू होती है तो हमारे मॉक टेस्ट में भी वही स्कीम लागू होती है, ताकि आपकी तैयारी असली परीक्षा जैसी हो।" },
      { q: "क्या मैं मोबाइल से टेस्ट दे सकता हूं?", a: "हां, टेस्ट मोबाइल और कंप्यूटर दोनों पर चलता है, लेकिन असली परीक्षा अनुभव के लिए कंप्यूटर या लैपटॉप पर प्रैक्टिस करने की सलाह दी जाती है।" },
      { q: "पैकेज खरीदने के बाद रिफंड मिलेगा?", a: "चूंकि टेस्ट एक्सेस डिजिटल है, एक बार टेस्ट शुरू करने के बाद रिफंड संभव नहीं है। इसीलिए खरीदने से पहले फ्री टेस्ट ज़रूर दें। एग्ज़ाम के दौरान किसी तकनीकी समस्या की शिकायत के लिए सपोर्ट से संपर्क करें।" },
    ],
    finalTitle: "आज ही अपना पहला मॉक टेस्ट दें",
    finalDesc: "बिल्कुल मुफ़्त, बिना कार्ड डिटेल के, सिर्फ़ 5 मिनट में शुरू करें।",
    finalCta: "फ्री टेस्ट शुरू करें →",
    footer: "ExamsExpress · MP पटवारी टेस्ट सीरीज़ — MPPEB से असंबद्ध एक स्वतंत्र प्रैक्टिस प्लेटफ़ॉर्म",
    footerLinks: { about: "हमारे बारे में", howItWorks: "यह कैसे काम करता है", disclaimer: "डिस्क्लेमर व नीतियाँ" },
  },
  en: {
    brandEn: "ExamsExpress",
    brandHi: "MP State-Level Exams",
    navCta: "Login / Register",
    eyebrow: "Based on the MPPEB pattern · 2026",
    heroTitlePre: "Don't take a computer-based test for the ",
    heroTitleAccent: "first time",
    heroTitlePost: " in the exam hall",
    heroLede:
      "A mock test that replicates the real MP Patwari online exam — the same timer, the same sections, the same screen. Your first full test is completely free, no card required.",
    ctaPrimary: "Start Free Test →",
    ctaGhost: "View Exam Pattern",
    stats: [
      { value: "200", label: "Total Marks" },
      { value: "3", label: "Hour Exam" },
      { value: "6", label: "Subjects Covered" },
      { value: "₹0", label: "First Test" },
    ],
    admitCard: {
      t1: "PRACTICE HALL TICKET",
      t2: "Practice Admit Card",
      name: "Candidate Name",
      role: "MP Patwari Recruitment Exam",
      rows: [
        { label: "Exam", value: "MOCK TEST 01" },
        { label: "Total Questions", value: "100" },
        { label: "Total Marks", value: "200" },
        { label: "Duration", value: "180 MIN" },
        { label: "Mode", value: "ONLINE" },
      ],
      stamp: "FREE TEST",
    },
    stepsKicker: "PROCESS",
    stepsTitle: "Get started in three steps",
    steps: [
      { num: "01 / LOGIN", title: "Create an account", desc: "Register with your mobile number in 30 seconds, no forms to fill." },
      { num: "02 / FREE TEST", title: "Take 1 full test free", desc: "A real exam-like interface — timer, section navigation, instant scorecard." },
      { num: "03 / PACKAGE", title: "Get 5, 10 or 20 tests", desc: "Choose a package based on your preparation and practice consistently." },
    ],
    patternKicker: "EXAM PATTERN",
    patternTitle: "Every mock test follows this exact pattern",
    patternSubjectHeader: "Subject",
    patternWeightHeader: "Weightage",
    patternRows: [
      { subject: "General Knowledge", weight: "High" },
      { subject: "General Math & Reasoning", weight: "High" },
      { subject: "General Hindi", weight: "Medium" },
      { subject: "General English", weight: "Medium" },
      { subject: "Computer Knowledge", weight: "Medium" },
      { subject: "Rural Economy & Panchayati Raj", weight: "Medium" },
    ],
    patternBig: "200",
    patternNote:
      "A 200-mark online exam, 3 hours in duration. The pattern is updated per MPPEB's official notification, so your preparation always matches the latest format.",
    whyKicker: "WHY IT MATTERS",
    whyTitle: "Without online practice, the real exam is a shock",
    whyCards: [
      { icon: "1", title: "Getting used to a screen", desc: "Many candidates select answers with a mouse for the first time in the exam hall. Here, you practice it beforehand." },
      { icon: "2", title: "Time pressure", desc: "Practicing with a real timer shows which section is taking longer, so there are no surprises on exam day." },
      { icon: "3", title: "Instant results", desc: "Get section-wise scores and weak areas right after every test, and plan your next round of preparation accordingly." },
    ],
    pricingKicker: "PACKAGES",
    pricingTitle: "First test free, then pick a package that fits your needs",
    plans: [
      { name: "Free Trial", amount: "₹0", per: "1 full test", features: ["Real exam interface", "Instant scorecard", "No card required"], cta: "Start Now" },
      { name: "Starter", amount: "₹399", per: "5 tests", features: ["5 full-length mock tests", "Section-wise analysis", "60-day validity"], cta: "Get Package" },
      { name: "Popular", amount: "₹799", per: "10 tests", features: ["10 full-length mock tests", "Detailed performance report", "90-day validity"], cta: "Get Package", tag: "MOST POPULAR" },
      { name: "Pro", amount: "₹1499", per: "20 tests", features: ["20 full-length mock tests", "Progress tracking", "120-day validity"], cta: "Get Package" },
    ],
    faqKicker: "FAQ",
    faqTitle: "Frequently Asked Questions",
    faqs: [
      { q: "Is this the official MPPEB exam?", a: "No, this is an independent practice platform. We are not affiliated with MPPEB — our tests are based only on the pattern and syllabus described in the official notification." },
      { q: "Is negative marking included?", a: "Yes, if the official exam applies negative marking, the same scheme applies to our mock tests, so your preparation matches the real exam." },
      { q: "Can I take the test on mobile?", a: "Yes, the test works on both mobile and computer, but for the most realistic exam experience, we recommend practicing on a computer or laptop." },
      { q: "Do I get a refund after buying a package?", a: "Since test access is digital, a refund isn't possible once a test has started. That's why we recommend taking the free test before buying. For a technical issue faced while taking an exam, please contact support." },
    ],
    finalTitle: "Take your first mock test today",
    finalDesc: "Completely free, no card required, get started in just 5 minutes.",
    finalCta: "Start Free Test →",
    footer: "ExamsExpress · MP Patwari Test Series — an independent practice platform, not affiliated with MPPEB",
    footerLinks: { about: "About", howItWorks: "How It Works", disclaimer: "Disclaimer & Policies" },
  },
} satisfies Record<Lang, unknown>;

export default content;
